# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy CalculatorAPI to Remote Server

on:
  workflow_dispatch:
    #branches:
      #- main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: |
          cd CalculatorAPI
          dotnet restore

      - name: Build project
        run: |
          cd CalculatorAPI
          dotnet build --configuration Release

          
      - name: Test project
        run: |
          cd CalculatorAPI
          dotnet test
          
      - name: Publish the application
        run: |
          cd CalculatorAPI
          dotnet publish --configuration Release --output ./publish

      - name: Deploy to test server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: ${{ secrets.TEST_SERVER_USER }}
          password: ${{ secrets.TEST_SERVER_PASSWORD }}
          source: CalculatorAPI/publish/
          target: D:\Websites\testapi
