# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy CalculatorAPI to Remote Server

on:
  workflow_dispatch:
    #branches:
      #- main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: |
          cd CalculatorAPI
          dotnet restore

      - name: Build project
        run: |
          cd CalculatorAPI
          dotnet build --configuration Release

          
      - name: Test project
        run: |
          cd CalculatorAPI
          dotnet test
          
      - name: Publish the application
        run: |
          cd CalculatorAPI
          dotnet publish --configuration Release --output ./publish
     # - name: List publish directory
      #  run: ls -la ./publish

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: eu-central-1.sftpcloud.io
          username: 6a9bb211cc174cf3aaae6a38f0bfe58f
          password:  IZHx4J7isAsnvvRCR3AAmP0VwPyIDf2p
